spring:
   cloud:
    gateway:
      discovery:
       locator:
        enabled: true
      routes:
        - id: bookms-route
          uri: lb://LIBRARY_BOOKMS
          predicates:
            - Path=/library_BookMs/**
          filters:
            - RewritePath=/library_BookMs/(?<segment>.*), /${segment}

        - id: issuerms-route
          uri: lb://issuerms
          predicates:
            - Path=/issuerms/**
          filters:
            - RewritePath=/issuerms/(?<segment>.*), /${segment}
   application:
    name: library_APIGateway
    
server:
  port: 8073

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8072/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
