spring:
   cloud:
    gateway:
      discovery:
       locator:
        enabled: true
      routes:
        - id: librarybookms-route
          uri: lb://LIBRARYBOOKMS
          predicates:
            - Path=/libraryBookMs/**
          filters:
            - RewritePath=/libraryBookMs/(?<segment>.*), /${segment}

        - id: libraryissuerms-route
          uri: lb://LIBRARYISSUERMS
          predicates:
            - Path=/libraryIssuerMs/**
          filters:
            - RewritePath=/libraryIssuerMs/(?<segment>.*), /${segment}
   application:
    name: library_APIGateway
    
server:
  port: 8073

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8072/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
